<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/stockadjustment/_show.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 12:00:27 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show StockAdjustment')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('stockadjustments.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$stockadjustment->id}}</td></tr>
		<tr><th>User Id</th><td>{{$stockadjustment->user_id}}</td></tr>
		<tr><th>Adjustment Type Id</th><td>{{$stockadjustment->adjustment_type_id}}</td></tr>
		<tr><th>Warehouse Id</th><td>{{$stockadjustment->warehouse_id}}</td></tr>
		<tr><th>Created At</th><td>{{$stockadjustment->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$stockadjustment->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
