<?php
/*
 * ProBot Version: 3.0
 * Laravel Version: 10x
 * Description: This source file "resources/views/order/_index.blade.php" was generated by ProBot AI.
 * Date: 2/19/2025 11:57:23 AM
 * Contact: towhid1@outlook.com
 */
?>
@extends('layout.erp.app')
@section('title', 'Manage Order')
@section('style')


@endsection
@section('page')

        <a class="btn btn-primary" href="{{ route('orders.create') }}">New Order</a>


    <table class="table table-hover text-nowrap">
        <thead>
            <tr>
                <th>Id</th>
                <th>Customer Id</th>
                <th>Order Total</th>
                <th>Discount</th>
                <th>Shipping Address</th>
                <th>Paid Amount</th>
                <th>Status Id</th>
                <th>Order Date</th>
                <th>Delivery Date</th>
                <th>Vat</th>
                <th>Remark</th>

                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($orders as $order)
                <tr>
                    <td>{{ $order->id }}</td>
                    <td>{{ $order->customer_id }}</td>
                    <td>{{ $order->order_total }}</td>
                    <td>{{ $order->discount }}</td>
                    <td>{{ $order->shipping_address }}</td>
                    <td>{{ $order->paid_amount }}</td>
                    <td>{{ $order->status_id }}</td>
                    <td>{{ $order->order_date }}</td>
                    <td>{{ $order->delivery_date }}</td>
                    <td>{{ $order->vat }}</td>
                    <td>{{ $order->remark }}</td>

                    <td>
                        <form action = "{{ route('orders.destroy', $order->id) }}" method = "post">
                            <a class= 'btn btn-primary' href = "{{ route('orders.show', $order->id) }}">View</a>
                            <a class= 'btn btn-success' href = "{{ route('orders.edit', $order->id) }}"> Edit </a>
                            @method('DELETE')
                            @csrf
                            <input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="d-flex justify-content-end mt-5">
        {!! $orders->links('pagination::bootstrap-5') !!}
    </div>
@endsection
@section('script')


@endsection
