<?php
/*
 * ProBot Version: 3.0
 * Laravel Version: 10x
 * Description: This source file "resources/views/purchasesdetail/_index.blade.php" was generated by ProBot AI.
 * Date: 2/19/2025 11:58:22 AM
 * Contact: towhid1@outlook.com
 */
?>
@extends('layout.erp.app')
@section('title', 'Order Report')
@section('style')


@endsection
@section('page')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">


                        <h2 class="mb-4">Order Report</h2>

                        <form method="POST" action="{{ url('/order-report') }}">
                            @csrf
                            <div class="row mb-3">
                                <div class="col-md-4">
                                    <label for="start_date" class="form-label">Start Date</label>
                                    <input type="date" id="start_date" name="start_date" class="form-control"
                                        value="{{ old('start_date', $startDate ?? '') }}" required>
                                </div>
                                <div class="col-md-4">
                                    <label for="end_date" class="form-label">End Date</label>
                                    <input type="date" id="end_date" name="end_date" class="form-control"
                                        value="{{ old('end_date', $endDate ?? '') }}" required>
                                </div>
                                <div class="col-md-4 d-flex align-items-end">
                                    <button type="submit" class="btn btn-primary">Generate Report</button>
                                </div>
                            </div>
                        </form>

                        @if (!empty($orders))
                            <table class="table table-bordered mt-4">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Customer</th>
                                        <th>Order Total</th>
                                        <th>Discount</th>
                                        <th>Shipping Address</th>
                                        <th>Paid Amount</th>
                                        <th>Status Id</th>
                                        <th>Order Date</th>
                                        <th>Delivery Date</th>
                                        <th>Vat</th>
                                        <th>Remark</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($orders as $order)
                                        <tr>
                                            <td>{{ $order->id }}</td>
                                            <td>{{ optional($order->customers)->name }}</td>
                                            <td>{{ $order->order_total }}</td>
                                            <td>{{ $order->discount }}</td>
                                            <td>{{ optional($order->customers)->address }}</td>
                                            <td>{{ $order->paid_amount }}</td>
                                            <td>{{ $order->status_id }}</td>
                                            <td>{{ $order->order_date }}</td>
                                            <td>{{ $order->delivery_date }}</td>
                                            <td>{{ $order->vat }}</td>
                                            <td>{{ $order->remark }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @else
                            <p class="mt-4 text-center">No purchases found for the selected date range.</p>
                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
