<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/stockadjustmentdetail/_show.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 12:01:00 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show StockAdjustmentDetail')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('stockadjustmentdetails.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$stockadjustmentdetail->id}}</td></tr>
		<tr><th>Stock Adjustment Id</th><td>{{$stockadjustmentdetail->stock_adjustment_id}}</td></tr>
		<tr><th>Product Id</th><td>{{$stockadjustmentdetail->product_id}}</td></tr>
		<tr><th>Qty</th><td>{{$stockadjustmentdetail->qty}}</td></tr>
		<tr><th>Price</th><td>{{$stockadjustmentdetail->price}}</td></tr>
		<tr><th>Created At</th><td>{{$stockadjustmentdetail->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$stockadjustmentdetail->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
