<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/paymentstatuse/_index.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:34:45 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage PaymentStatuse')
@section('style')


@endsection
@section('page')
<a href="{{route('paymentstatuses.create')}}">New PaymentStatuse</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($paymentstatuses as $paymentstatuse)
		<tr>
			<td>{{$paymentstatuse->id}}</td>
			<td>{{$paymentstatuse->name}}</td>
			<td>{{$paymentstatuse->created_at}}</td>
			<td>{{$paymentstatuse->updated_at}}</td>

			<td>
			<form action = "{{route('paymentstatuses.destroy',$paymentstatuse->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('paymentstatuses.show',$paymentstatuse->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('paymentstatuses.edit',$paymentstatuse->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
