<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/paymentstatuse/_show.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:34:45 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show PaymentStatuse')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('paymentstatuses.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$paymentstatuse->id}}</td></tr>
		<tr><th>Name</th><td>{{$paymentstatuse->name}}</td></tr>
		<tr><th>Created At</th><td>{{$paymentstatuse->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$paymentstatuse->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
