<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/product/_create.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 11:56:53 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Product')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('products.index')}}">Manage</a>
<form action="{{route('products.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="photo" class="col-sm-2 col-form-label">Photo</label>
	<div class="col-sm-10">
		<input type = "file" class="form-control" name="photo" id="photo" placeholder="Photo">
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" id="price" placeholder="Price">
	</div>
</div>
<div class="row mb-3">
	<label for="offer_price" class="col-sm-2 col-form-label">Offer Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="offer_price" id="offer_price" placeholder="Offer Price">
	</div>
</div>
<div class="row mb-3">
	<label for="category_id" class="col-sm-2 col-form-label">Category</label>
	<div class="col-sm-10">
		<select class="form-control" name="category_id" id="category_id">
			@foreach($categories as $category)
				<option value="{{$category->id}}">{{$category->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="uom_id" class="col-sm-2 col-form-label">Uom</label>
	<div class="col-sm-10">
		<select class="form-control" name="uom_id" id="uom_id">
			@foreach($uom as $uom)
				<option value="{{$uom->id}}">{{$uom->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="barcode" class="col-sm-2 col-form-label">Barcode</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="barcode" id="barcode" placeholder="Barcode">
	</div>
</div>
<div class="row mb-3">
	<label for="sku" class="col-sm-2 col-form-label">Sku</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="sku" id="sku" placeholder="Sku">
	</div>
</div>
<div class="row mb-3">
	<label for="manufacturer_id" class="col-sm-2 col-form-label">Manufacturer</label>
	<div class="col-sm-10">
		<select class="form-control" name="manufacturer_id" id="manufacturer_id">
			@foreach($manufacturers as $manufacturer)
				<option value="{{$manufacturer->id}}">{{$manufacturer->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="description" class="col-sm-2 col-form-label">Description</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="description" id="description" placeholder="Description">
	</div>
</div>
<div class="row mb-3">
	<label for="weight" class="col-sm-2 col-form-label">Weight</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="weight" id="weight" placeholder="Weight">
	</div>
</div>
<div class="row mb-3">
	<label for="size" class="col-sm-2 col-form-label">Size</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="size" id="size" placeholder="Size">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
