<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/product/_index.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 11:56:53 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Product')
@section('style')


@endsection
@section('page')
<a class="btn btn-success" href="{{route('products.create')}}">New Product</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Photo</th>
			<th>Price</th>
			<th>Offer Price</th>
			<th>Category</th>
			{{-- <th>Uom Id</th> --}}
			{{-- <th>Barcode</th> --}}
			{{-- <th>Sku</th> --}}
			{{-- <th>Manufacturer Id</th> --}}
			{{-- <th>Description</th> --}}
			{{-- <th>Weight</th> --}}
			<th>Size</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($products as $product)
		<tr>
			<td>{{$product->id}}</td>
			<td>{{$product->name}}</td>
			<td><img src="{{asset('img/'.$product->photo)}}" width="100" /></td>
			<td>{{$product->price}}</td>
			<td>{{$product->offer_price}}</td>
			<td>{{optional ($product->categories)->name}}</td>
			{{-- <td>{{$product->uom_id}}</td> --}}
			{{-- <td>{{$product->barcode}}</td> --}}
			{{-- <td>{{$product->sku}}</td> --}}
			{{-- <td>{{$product->manufacturer_id}}</td> --}}
			{{-- <td>{{$product->description}}</td> --}}
			{{-- <td>{{$product->weight}}</td> --}}
			<td>{{$product->size}}</td>

			<td>
			<form action = "{{route('products.destroy',$product->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('products.show',$product->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('products.edit',$product->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>

<div class="d-flex justify-content-end mt-5">
    {!! $products->links('pagination::bootstrap-5') !!}
</div>
@endsection
@section('script')


@endsection
