<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/orderdetail/_index.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 11:57:43 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage OrderDetail')
@section('style')


@endsection
@section('page')
<a href="{{route('orderdetails.create')}}">New OrderDetail</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Order Id</th>
			<th>Product Id</th>
			<th>Qty</th>
			<th>Price</th>
			<th>Vat</th>
			<th>Uom Id</th>
			<th>Discount</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($orderdetails as $orderdetail)
		<tr>
			<td>{{$orderdetail->id}}</td>
			<td>{{$orderdetail->order_id}}</td>
			<td>{{$orderdetail->product_id}}</td>
			<td>{{$orderdetail->qty}}</td>
			<td>{{$orderdetail->price}}</td>
			<td>{{$orderdetail->vat}}</td>
			<td>{{$orderdetail->uom_id}}</td>
			<td>{{$orderdetail->discount}}</td>

			<td>
			<form action = "{{route('orderdetails.destroy',$orderdetail->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('orderdetails.show',$orderdetail->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('orderdetails.edit',$orderdetail->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
