<?php
/*
 * ProBot Version: 3.0
 * Laravel Version: 10x
 * Description: This source file "resources/views/purchasesdetail/_index.blade.php" was generated by ProBot AI.
 * Date: 2/19/2025 11:58:22 AM
 * Contact: towhid1@outlook.com
 */
?>
@extends('layout.erp.app')
@section('title', 'Stock Report')
@section('style')


@endsection
@section('page')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">


                        <h2 class="mb-4">Stock Report</h2>

                        <form method="POST" action="{{ url('/stock-report') }}">
                            @csrf
                            <div class="row mb-3">
                                <div class="col-md-3">
                                    <label for="start_date" class="form-label">Start Date</label>
                                    <input type="date" id="start_date" name="start_date" class="form-control"
                                        value="{{ old('start_date', $startDate ?? '') }}" required>
                                </div>
                                <div class="col-md-3">
                                    <label for="end_date" class="form-label">End Date</label>
                                    <input type="date" id="end_date" name="end_date" class="form-control"
                                        value="{{ old('end_date', $endDate ?? '') }}" required>
                                </div>
                                <div class="col-md-3">
                                    <label for="remark" class="form-label">Remark</label>
                                    <select id="remark" name="remark" class="form-control">
                                        <option value="">All</option>
                                        <option value="Sales"
                                            {{ old('remark', $remark ?? '') == 'Sales' ? 'selected' : '' }}>Sales</option>
                                        <option value="Purchase"
                                            {{ old('remark', $remark ?? '') == 'Purchase' ? 'selected' : '' }}>Purchase
                                        </option>
                                    </select>
                                </div>

                                <div class="col-md-3">
                                    <label for="product_id" class="form-label">Product</label>
                                    <select id="product_id" name="product_id" class="form-control">
                                        <option value="">All Products</option>
                                        @foreach ($products as $product)
                                            <option value="{{ $product->id }}"
                                                {{ old('product_id', $product_id ?? '') == $product->id ? 'selected' : '' }}>
                                                {{ $product->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="col-md-3 d-flex align-items-end">
                                    <button type="submit" class="btn btn-primary">Generate Report</button>
                                </div>
                            </div>
                        </form>


                        @if (!empty($stocks))
                            <table class="table table-bordered mt-4">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Product</th>
                                        <th>Qty</th>
                                        <th>Remark</th>
                                        <th>Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($stocks as $stock)
                                        <tr>
                                            <th>{{ $stock->id }}</th>
                                            <th>{{ optional($stock->products)->name }}</th>
                                            <th>{{ $stock->qty }}</th>
                                            <th>{{ $stock->remark }}</th>
                                            <th>{{ $stock->updated_at }}</th>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @else
                            <p class="mt-4 text-center">No Stocks found for the selected date range.</p>
                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
