<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchasereturn/_edit.blade.php" was generated by ProBot AI.
* Date: 3/5/2025 11:31:00 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit PurchaseReturn')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('purchasereturns.index')}}">Manage</a>
<form action="{{route('purchasereturns.update',$purchasereturn)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="purchases_id" class="col-sm-2 col-form-label">Purchases</label>
	<div class="col-sm-10">
		<select class="form-control" name="purchases_id" id="purchases_id">
			@foreach($purchasess as $purchases)
				@if($purchases->id==$purchasereturn->purchases_id)
					<option value="{{$purchases->id}}" selected>{{$purchases->name}}</option>
				@else
					<option value="{{$purchases->id}}">{{$purchases->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="supplier_id" class="col-sm-2 col-form-label">Supplier</label>
	<div class="col-sm-10">
		<select class="form-control" name="supplier_id" id="supplier_id">
			@foreach($suppliers as $supplier)
				@if($supplier->id==$purchasereturn->supplier_id)
					<option value="{{$supplier->id}}" selected>{{$supplier->name}}</option>
				@else
					<option value="{{$supplier->id}}">{{$supplier->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="purchase_status_id" class="col-sm-2 col-form-label">Purchase_Status</label>
	<div class="col-sm-10">
		<select class="form-control" name="purchase_status_id" id="purchase_status_id">
			@foreach($purchase_statuss as $purchase_status)
				@if($purchase_status->id==$purchasereturn->purchase_status_id)
					<option value="{{$purchase_status->id}}" selected>{{$purchase_status->name}}</option>
				@else
					<option value="{{$purchase_status->id}}">{{$purchase_status->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="order_total" class="col-sm-2 col-form-label">Order Total</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="order_total" value="{{$purchasereturn->order_total}}" id="order_total" placeholder="Order Total">
	</div>
</div>
<div class="row mb-3">
	<label for="paid_amount" class="col-sm-2 col-form-label">Paid Amount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="paid_amount" value="{{$purchasereturn->paid_amount}}" id="paid_amount" placeholder="Paid Amount">
	</div>
</div>
<div class="row mb-3">
	<label for="discount" class="col-sm-2 col-form-label">Discount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="discount" value="{{$purchasereturn->discount}}" id="discount" placeholder="Discount">
	</div>
</div>
<div class="row mb-3">
	<label for="vat" class="col-sm-2 col-form-label">Vat</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="vat" value="{{$purchasereturn->vat}}" id="vat" placeholder="Vat">
	</div>
</div>
<div class="row mb-3">
	<label for="date" class="col-sm-2 col-form-label">Date</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="date" value="{{$purchasereturn->date}}" id="date" placeholder="Date">
	</div>
</div>
<div class="row mb-3">
	<label for="shipping_address" class="col-sm-2 col-form-label">Shipping Address</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="shipping_address" value="{{$purchasereturn->shipping_address}}" id="shipping_address" placeholder="Shipping Address">
	</div>
</div>
<div class="row mb-3">
	<label for="description" class="col-sm-2 col-form-label">Description</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="description" value="{{$purchasereturn->description}}" id="description" placeholder="Description">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
