<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchasereturn/_index.blade.php" was generated by ProBot AI.
* Date: 3/5/2025 11:31:00 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage PurchaseReturn')
@section('style')


@endsection
@section('page')
<a href="{{route('purchasereturns.create')}}">New PurchaseReturn</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Purchases Id</th>
			<th>Supplier Id</th>
			<th>Purchase Status Id</th>
			<th>Order Total</th>
			<th>Paid Amount</th>
			<th>Discount</th>
			<th>Vat</th>
			<th>Date</th>
			<th>Shipping Address</th>
			<th>Description</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($purchasereturns as $purchasereturn)
		<tr>
			<td>{{$purchasereturn->id}}</td>
			<td>{{$purchasereturn->purchases_id}}</td>
			<td>{{$purchasereturn->supplier_id}}</td>
			<td>{{$purchasereturn->purchase_status_id}}</td>
			<td>{{$purchasereturn->order_total}}</td>
			<td>{{$purchasereturn->paid_amount}}</td>
			<td>{{$purchasereturn->discount}}</td>
			<td>{{$purchasereturn->vat}}</td>
			<td>{{$purchasereturn->date}}</td>
			<td>{{$purchasereturn->shipping_address}}</td>
			<td>{{$purchasereturn->description}}</td>
			<td>{{$purchasereturn->created_at}}</td>
			<td>{{$purchasereturn->updated_at}}</td>

			<td>
			<form action = "{{route('purchasereturns.destroy',$purchasereturn->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('purchasereturns.show',$purchasereturn->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('purchasereturns.edit',$purchasereturn->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
