<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchasereturn/_show.blade.php" was generated by ProBot AI.
* Date: 3/5/2025 11:31:00 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show PurchaseReturn')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('purchasereturns.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$purchasereturn->id}}</td></tr>
		<tr><th>Purchases Id</th><td>{{$purchasereturn->purchases_id}}</td></tr>
		<tr><th>Supplier Id</th><td>{{$purchasereturn->supplier_id}}</td></tr>
		<tr><th>Purchase Status Id</th><td>{{$purchasereturn->purchase_status_id}}</td></tr>
		<tr><th>Order Total</th><td>{{$purchasereturn->order_total}}</td></tr>
		<tr><th>Paid Amount</th><td>{{$purchasereturn->paid_amount}}</td></tr>
		<tr><th>Discount</th><td>{{$purchasereturn->discount}}</td></tr>
		<tr><th>Vat</th><td>{{$purchasereturn->vat}}</td></tr>
		<tr><th>Date</th><td>{{$purchasereturn->date}}</td></tr>
		<tr><th>Shipping Address</th><td>{{$purchasereturn->shipping_address}}</td></tr>
		<tr><th>Description</th><td>{{$purchasereturn->description}}</td></tr>
		<tr><th>Created At</th><td>{{$purchasereturn->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$purchasereturn->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
