<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchase/_show.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 11:58:05 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Purchase')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('purchases.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$purchase->id}}</td></tr>
		<tr><th>Supplier Id</th><td>{{$purchase->supplier_id}}</td></tr>
		<tr><th>Status Id</th><td>{{$purchase->status_id}}</td></tr>
		<tr><th>Order Total</th><td>{{$purchase->order_total}}</td></tr>
		<tr><th>Paid Amount</th><td>{{$purchase->paid_amount}}</td></tr>
		<tr><th>Discount</th><td>{{$purchase->discount}}</td></tr>
		<tr><th>Vat</th><td>{{$purchase->vat}}</td></tr>
		<tr><th>Photo</th><td><img src="{{asset('img/'.$purchase->photo)}}" width="100" /></td></tr>
		<tr><th>Date</th><td>{{$purchase->date}}</td></tr>
		<tr><th>Shipping Address</th><td>{{$purchase->shipping_address}}</td></tr>
		<tr><th>Description</th><td>{{$purchase->description}}</td></tr>
		<tr><th>Created At</th><td>{{$purchase->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$purchase->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
