<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/warehouse/_index.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 9:26:19 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Warehouse')
@section('style')


@endsection
@section('page')
<a href="{{route('warehouses.create')}}">New Warehouse</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Phone</th>
			<th>Location</th>
			<th>Address</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($warehouses as $warehouse)
		<tr>
			<td>{{$warehouse->id}}</td>
			<td>{{$warehouse->name}}</td>
			<td>{{$warehouse->phone}}</td>
			<td>{{$warehouse->location}}</td>
			<td>{{$warehouse->address}}</td>

			<td>
			<form action = "{{route('warehouses.destroy',$warehouse->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('warehouses.show',$warehouse->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('warehouses.edit',$warehouse->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
