<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/warehouse/_show.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 9:26:19 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Warehouse')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('warehouses.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$warehouse->id}}</td></tr>
		<tr><th>Name</th><td>{{$warehouse->name}}</td></tr>
		<tr><th>Phone</th><td>{{$warehouse->phone}}</td></tr>
		<tr><th>Location</th><td>{{$warehouse->location}}</td></tr>
		<tr><th>Address</th><td>{{$warehouse->address}}</td></tr>
		<tr><th>Created At</th><td>{{$warehouse->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$warehouse->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
