<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchasesdetail/_edit.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 11:58:22 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit PurchasesDetail')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('purchasesdetails.index')}}">Manage</a>
<form action="{{route('purchasesdetails.update',$purchasesdetail)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="purchases_id" class="col-sm-2 col-form-label">Purchases</label>
	<div class="col-sm-10">
		<select class="form-control" name="purchases_id" id="purchases_id">
			@foreach($purchasess as $purchases)
				@if($purchases->id==$purchasesdetail->purchases_id)
					<option value="{{$purchases->id}}" selected>{{$purchases->name}}</option>
				@else
					<option value="{{$purchases->id}}">{{$purchases->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="product_id" class="col-sm-2 col-form-label">Product</label>
	<div class="col-sm-10">
		<select class="form-control" name="product_id" id="product_id">
			@foreach($products as $product)
				@if($product->id==$purchasesdetail->product_id)
					<option value="{{$product->id}}" selected>{{$product->name}}</option>
				@else
					<option value="{{$product->id}}">{{$product->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="qty" class="col-sm-2 col-form-label">Qty</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="qty" value="{{$purchasesdetail->qty}}" id="qty" placeholder="Qty">
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" value="{{$purchasesdetail->price}}" id="price" placeholder="Price">
	</div>
</div>
<div class="row mb-3">
	<label for="discount" class="col-sm-2 col-form-label">Discount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="discount" value="{{$purchasesdetail->discount}}" id="discount" placeholder="Discount">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
