<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchasesdetail/_index.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 11:58:22 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage PurchasesDetail')
@section('style')


@endsection
@section('page')
<a href="{{route('purchasesdetails.create')}}">New PurchasesDetail</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Purchases Id</th>
			<th>Product Id</th>
			<th>Qty</th>
			<th>Price</th>
			<th>Discount</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($purchasesdetails as $purchasesdetail)
		<tr>
			<td>{{$purchasesdetail->id}}</td>
			<td>{{$purchasesdetail->purchases_id}}</td>
			<td>{{$purchasesdetail->product_id}}</td>
			<td>{{$purchasesdetail->qty}}</td>
			<td>{{$purchasesdetail->price}}</td>
			<td>{{$purchasesdetail->discount}}</td>

			<td>
			<form action = "{{route('purchasesdetails.destroy',$purchasesdetail->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('purchasesdetails.show',$purchasesdetail->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('purchasesdetails.edit',$purchasesdetail->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
