<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchasesdetail/_show.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 11:58:22 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show PurchasesDetail')
@section('style')


@endsection
@section('page')

<a class='btn btn-success' href="{{route('purchasesdetails.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$purchasesdetail->id}}</td></tr>
		<tr><th>Purchases Id</th><td>{{$purchasesdetail->purchases_id}}</td></tr>
		<tr><th>Product Id</th><td>{{$purchasesdetail->product_id}}</td></tr>
		<tr><th>Qty</th><td>{{$purchasesdetail->qty}}</td></tr>
		<tr><th>Price</th><td>{{$purchasesdetail->price}}</td></tr>
		<tr><th>Discount</th><td>{{$purchasesdetail->discount}}</td></tr>
		<tr><th>Created At</th><td>{{$purchasesdetail->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$purchasesdetail->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
