<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/orderstatuse/_show.blade.php" was generated by ProBot AI.
* Date: 3/4/2025 10:28:36 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show OrderStatuse')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('orderstatuses.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$orderstatuse->id}}</td></tr>
		<tr><th>Name</th><td>{{$orderstatuse->name}}</td></tr>
		<tr><th>Description</th><td>{{$orderstatuse->description}}</td></tr>
		<tr><th>Created At</th><td>{{$orderstatuse->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$orderstatuse->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
