<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchasestatuse/_index.blade.php" was generated by ProBot AI.
* Date: 3/5/2025 10:48:34 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage PurchaseStatuse')
@section('style')


@endsection
@section('page')
<a href="{{route('purchasestatuses.create')}}">New PurchaseStatuse</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($purchasestatuses as $purchasestatuse)
		<tr>
			<td>{{$purchasestatuse->id}}</td>
			<td>{{$purchasestatuse->name}}</td>
			<td>{{$purchasestatuse->created_at}}</td>
			<td>{{$purchasestatuse->updated_at}}</td>

			<td>
			<form action = "{{route('purchasestatuses.destroy',$purchasestatuse->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('purchasestatuses.show',$purchasestatuse->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('purchasestatuses.edit',$purchasestatuse->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
