<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchasestatuse/_show.blade.php" was generated by ProBot AI.
* Date: 3/5/2025 10:48:34 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show PurchaseStatuse')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('purchasestatuses.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$purchasestatuse->id}}</td></tr>
		<tr><th>Name</th><td>{{$purchasestatuse->name}}</td></tr>
		<tr><th>Created At</th><td>{{$purchasestatuse->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$purchasestatuse->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
