<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/transactiontype/_show.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 11:59:10 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show TransactionType')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('transactiontypes.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$transactiontype->id}}</td></tr>
		<tr><th>Name</th><td>{{$transactiontype->name}}</td></tr>
		<tr><th>Factor</th><td>{{$transactiontype->factor}}</td></tr>
		<tr><th>Created At</th><td>{{$transactiontype->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$transactiontype->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
