<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchasereturndetail/_index.blade.php" was generated by ProBot AI.
* Date: 3/5/2025 11:31:32 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage PurchaseReturnDetail')
@section('style')


@endsection
@section('page')
<a href="{{route('purchasereturndetails.create')}}">New PurchaseReturnDetail</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Purchase Return Id</th>
			<th>Product Id</th>
			<th>Qty</th>
			<th>Price</th>
			<th>Discount</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($purchasereturndetails as $purchasereturndetail)
		<tr>
			<td>{{$purchasereturndetail->id}}</td>
			<td>{{$purchasereturndetail->purchase_return_id}}</td>
			<td>{{$purchasereturndetail->product_id}}</td>
			<td>{{$purchasereturndetail->qty}}</td>
			<td>{{$purchasereturndetail->price}}</td>
			<td>{{$purchasereturndetail->discount}}</td>
			<td>{{$purchasereturndetail->created_at}}</td>
			<td>{{$purchasereturndetail->updated_at}}</td>

			<td>
			<form action = "{{route('purchasereturndetails.destroy',$purchasereturndetail->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('purchasereturndetails.show',$purchasereturndetail->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('purchasereturndetails.edit',$purchasereturndetail->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
