<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchasereturndetail/_show.blade.php" was generated by ProBot AI.
* Date: 3/5/2025 11:31:32 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show PurchaseReturnDetail')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('purchasereturndetails.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$purchasereturndetail->id}}</td></tr>
		<tr><th>Purchase Return Id</th><td>{{$purchasereturndetail->purchase_return_id}}</td></tr>
		<tr><th>Product Id</th><td>{{$purchasereturndetail->product_id}}</td></tr>
		<tr><th>Qty</th><td>{{$purchasereturndetail->qty}}</td></tr>
		<tr><th>Price</th><td>{{$purchasereturndetail->price}}</td></tr>
		<tr><th>Discount</th><td>{{$purchasereturndetail->discount}}</td></tr>
		<tr><th>Created At</th><td>{{$purchasereturndetail->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$purchasereturndetail->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
