<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_OrderStatuseController.php" was generated by ProBot AI.
* Date: 3/4/2025 10:28:35 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\OrderStatuse;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class OrderStatuseController extends Controller{
	public function index(){
		$orderstatuses = OrderStatuse::paginate(10);
		return view("pages.erp.orderstatuse.index",["orderstatuses"=>$orderstatuses]);
	}
	public function create(){
		return view("pages.erp.orderstatuse.create",[]);
	}
	public function store(Request $request){
		//OrderStatuse::create($request->all());
		$orderstatuse = new OrderStatuse;
		$orderstatuse->name=$request->name;
		$orderstatuse->description=$request->description;
date_default_timezone_set("Asia/Dhaka");
		$orderstatuse->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$orderstatuse->updated_at=date('Y-m-d H:i:s');

		$orderstatuse->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$orderstatuse = OrderStatuse::find($id);
		return view("pages.erp.orderstatuse.show",["orderstatuse"=>$orderstatuse]);
	}
	public function edit(OrderStatuse $orderstatuse){
		return view("pages.erp.orderstatuse.edit",["orderstatuse"=>$orderstatuse,]);
	}
	public function update(Request $request,OrderStatuse $orderstatuse){
		//OrderStatuse::update($request->all());
		$orderstatuse = OrderStatuse::find($orderstatuse->id);
		$orderstatuse->name=$request->name;
		$orderstatuse->description=$request->description;
date_default_timezone_set("Asia/Dhaka");
		$orderstatuse->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$orderstatuse->updated_at=date('Y-m-d H:i:s');

		$orderstatuse->save();

		return redirect()->route("orderstatuses.index")->with('success','Updated Successfully.');
	}
	public function destroy(OrderStatuse $orderstatuse){
		$orderstatuse->delete();
		return redirect()->route("orderstatuses.index")->with('success', 'Deleted Successfully.');
	}
}
?>
