<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PaymentStatuseController.php" was generated by ProBot AI.
* Date: 3/3/2025 11:34:35 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\PaymentStatuse;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class PaymentStatuseController extends Controller{
	public function index(){
		$paymentstatuses = PaymentStatuse::paginate(10);
		return view("pages.erp.paymentstatuse.index",["paymentstatuses"=>$paymentstatuses]);
	}
	public function create(){
		return view("pages.erp.paymentstatuse.create",[]);
	}
	public function store(Request $request){
		//PaymentStatuse::create($request->all());
		$paymentstatuse = new PaymentStatuse;
		$paymentstatuse->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$paymentstatuse->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$paymentstatuse->updated_at=date('Y-m-d H:i:s');

		$paymentstatuse->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$paymentstatuse = PaymentStatuse::find($id);
		return view("pages.erp.paymentstatuse.show",["paymentstatuse"=>$paymentstatuse]);
	}
	public function edit(PaymentStatuse $paymentstatuse){
		return view("pages.erp.paymentstatuse.edit",["paymentstatuse"=>$paymentstatuse,]);
	}
	public function update(Request $request,PaymentStatuse $paymentstatuse){
		//PaymentStatuse::update($request->all());
		$paymentstatuse = PaymentStatuse::find($paymentstatuse->id);
		$paymentstatuse->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$paymentstatuse->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$paymentstatuse->updated_at=date('Y-m-d H:i:s');

		$paymentstatuse->save();

		return redirect()->route("paymentstatuses.index")->with('success','Updated Successfully.');
	}
	public function destroy(PaymentStatuse $paymentstatuse){
		$paymentstatuse->delete();
		return redirect()->route("paymentstatuses.index")->with('success', 'Deleted Successfully.');
	}
}
?>
