<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PurchaseReturnDetailController.php" was generated by ProBot AI.
* Date: 3/5/2025 11:31:30 AM
* Contact: towhid1@outlook.com
*/

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\PurchaseReturnDetail;
use App\Models\Purchase_Return;
use App\Models\Product;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;

class PurchaseReturnDetailController extends Controller
{
    public function index()
    {
        $purchasereturndetails = PurchaseReturnDetail::paginate(10);
        return view("pages.erp.purchasereturndetail.index", ["purchasereturndetails" => $purchasereturndetails]);
    }
    public function create()
    {
        return view("pages.erp.purchasereturndetail.create", ["purchase_returns" => Purchase_Return::all(), "products" => Product::all()]);
    }
    public function store(Request $request)
    {
        //PurchaseReturnDetail::create($request->all());
        $purchasereturndetail = new PurchaseReturnDetail;
        $purchasereturndetail->purchase_return_id = $request->purchase_return_id;
        $purchasereturndetail->product_id = $request->product_id;
        $purchasereturndetail->qty = $request->qty;
        $purchasereturndetail->price = $request->price;
        $purchasereturndetail->discount = $request->discount;
        date_default_timezone_set("Asia/Dhaka");
        $purchasereturndetail->created_at = date('Y-m-d H:i:s');
        date_default_timezone_set("Asia/Dhaka");
        $purchasereturndetail->updated_at = date('Y-m-d H:i:s');

        $purchasereturndetail->save();

        return back()->with('success', 'Created Successfully.');
    }
    public function show($id)
    {
        $purchasereturndetail = PurchaseReturnDetail::find($id);
        return view("pages.erp.purchasereturndetail.show", ["purchasereturndetail" => $purchasereturndetail]);
    }
    public function edit(PurchaseReturnDetail $purchasereturndetail)
    {
        return view("pages.erp.purchasereturndetail.edit", ["purchasereturndetail" => $purchasereturndetail, "purchase_returns" => Purchase_Return::all(), "products" => Product::all()]);
    }
    public function update(Request $request, PurchaseReturnDetail $purchasereturndetail)
    {
        //PurchaseReturnDetail::update($request->all());
        $purchasereturndetail = PurchaseReturnDetail::find($purchasereturndetail->id);
        $purchasereturndetail->purchase_return_id = $request->purchase_return_id;
        $purchasereturndetail->product_id = $request->product_id;
        $purchasereturndetail->qty = $request->qty;
        $purchasereturndetail->price = $request->price;
        $purchasereturndetail->discount = $request->discount;
        date_default_timezone_set("Asia/Dhaka");
        $purchasereturndetail->created_at = date('Y-m-d H:i:s');
        date_default_timezone_set("Asia/Dhaka");
        $purchasereturndetail->updated_at = date('Y-m-d H:i:s');

        $purchasereturndetail->save();

        return redirect()->route("purchasereturndetails.index")->with('success', 'Updated Successfully.');
    }
    public function destroy(PurchaseReturnDetail $purchasereturndetail)
    {
        $purchasereturndetail->delete();
        return redirect()->route("purchasereturndetails.index")->with('success', 'Deleted Successfully.');
    }
}
