<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PurchaseStatuseController.php" was generated by ProBot AI.
* Date: 3/5/2025 10:48:33 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\PurchaseStatuse;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class PurchaseStatuseController extends Controller{
	public function index(){
		$purchasestatuses = PurchaseStatuse::paginate(10);
		return view("pages.erp.purchasestatuse.index",["purchasestatuses"=>$purchasestatuses]);
	}
	public function create(){
		return view("pages.erp.purchasestatuse.create",[]);
	}
	public function store(Request $request){
		//PurchaseStatuse::create($request->all());
		$purchasestatuse = new PurchaseStatuse;
		$purchasestatuse->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$purchasestatuse->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$purchasestatuse->updated_at=date('Y-m-d H:i:s');

		$purchasestatuse->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$purchasestatuse = PurchaseStatuse::find($id);
		return view("pages.erp.purchasestatuse.show",["purchasestatuse"=>$purchasestatuse]);
	}
	public function edit(PurchaseStatuse $purchasestatuse){
		return view("pages.erp.purchasestatuse.edit",["purchasestatuse"=>$purchasestatuse,]);
	}
	public function update(Request $request,PurchaseStatuse $purchasestatuse){
		//PurchaseStatuse::update($request->all());
		$purchasestatuse = PurchaseStatuse::find($purchasestatuse->id);
		$purchasestatuse->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$purchasestatuse->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$purchasestatuse->updated_at=date('Y-m-d H:i:s');

		$purchasestatuse->save();

		return redirect()->route("purchasestatuses.index")->with('success','Updated Successfully.');
	}
	public function destroy(PurchaseStatuse $purchasestatuse){
		$purchasestatuse->delete();
		return redirect()->route("purchasestatuses.index")->with('success', 'Deleted Successfully.');
	}
}
?>
