<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PurchasesDetailController.php" was generated by ProBot AI.
* Date: 2/19/2025 11:58:21 AM
* Contact: towhid1@outlook.com
*/

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\PurchasesDetail;
use App\Models\Purchases;
use App\Models\Product;
use App\Models\Purchase;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;

class PurchasesDetailController extends Controller
{
    public function index()
    {
        $purchasesdetails = PurchasesDetail::paginate(10);
        return view("pages.erp.purchasesdetail.index", ["purchasesdetails" => $purchasesdetails]);
    }
    public function create()
    {
        return view("pages.erp.purchasesdetail.create", ["purchasess" => Purchase::all(), "products" => Product::all()]);
    }
    public function store(Request $request)
    {
        //PurchasesDetail::create($request->all());
        $purchasesdetail = new PurchasesDetail;
        $purchasesdetail->purchases_id = $request->purchases_id;
        $purchasesdetail->product_id = $request->product_id;
        $purchasesdetail->qty = $request->qty;
        $purchasesdetail->price = $request->price;
        $purchasesdetail->discount = $request->discount;
        date_default_timezone_set("Asia/Dhaka");
        $purchasesdetail->created_at = date('Y-m-d H:i:s');
        date_default_timezone_set("Asia/Dhaka");
        $purchasesdetail->updated_at = date('Y-m-d H:i:s');

        $purchasesdetail->save();

        return back()->with('success', 'Created Successfully.');
    }
    public function show($id)
    {
        $purchasesdetail = PurchasesDetail::find($id);
        return view("pages.erp.purchasesdetail.show", ["purchasesdetail" => $purchasesdetail]);
    }
    public function edit(PurchasesDetail $purchasesdetail)
    {
        return view("pages.erp.purchasesdetail.edit", ["purchasesdetail" => $purchasesdetail, "purchasess" => Purchase::all(), "products" => Product::all()]);
    }
    public function update(Request $request, PurchasesDetail $purchasesdetail)
    {
        //PurchasesDetail::update($request->all());
        $purchasesdetail = PurchasesDetail::find($purchasesdetail->id);
        $purchasesdetail->purchases_id = $request->purchases_id;
        $purchasesdetail->product_id = $request->product_id;
        $purchasesdetail->qty = $request->qty;
        $purchasesdetail->price = $request->price;
        $purchasesdetail->discount = $request->discount;
        date_default_timezone_set("Asia/Dhaka");
        $purchasesdetail->created_at = date('Y-m-d H:i:s');
        date_default_timezone_set("Asia/Dhaka");
        $purchasesdetail->updated_at = date('Y-m-d H:i:s');

        $purchasesdetail->save();

        return redirect()->route("purchasesdetails.index")->with('success', 'Updated Successfully.');
    }
    public function destroy(PurchasesDetail $purchasesdetail)
    {
        $purchasesdetail->delete();
        return redirect()->route("purchasesdetails.index")->with('success', 'Deleted Successfully.');
    }
}
