<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Manufacturer.php" was generated by ProBot AI.
* Date: 2/18/2025 1:03:21 PM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Manufacturer extends Model{


}
?>
