<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_OrderStatuse.php" was generated by ProBot AI.
* Date: 3/4/2025 10:28:36 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class OrderStatuse extends Model{
    protected $table="order_statuses";
    protected $fillable =['name', 'description'];


}
?>
