<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_PaymentStatuse.php" was generated by ProBot AI.
* Date: 3/3/2025 11:34:45 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class PaymentStatuse extends Model{
    protected $table="payment_statuses";
    protected $fillable =['name'];
}
?>
