<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_PurchasesDetail.php" was generated by ProBot AI.
* Date: 2/19/2025 11:58:22 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class PurchasesDetail extends Model{
    protected $table="purchases_details";
    protected $fillable =['purchases_id', 'product_id', 'qty', 'price', 'discount', 'uom_id', 'discount'];

    public function products(){
        return  $this->belongsTo(Product::class, 'product_id');
    }
    public function product(){
        return  $this->belongsTo(Product::class, 'product_id');
    }

}
?>
