<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_PurchaseStatuse.php" was generated by ProBot AI.
* Date: 3/5/2025 10:48:34 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class PurchaseStatuse extends Model{
    protected $table="purchase_statuses";
    protected $fillable =['name'];

}
?>
