<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_PurchaseReturn.php" was generated by ProBot AI.
* Date: 3/5/2025 11:31:00 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class PurchaseReturn extends Model{
    protected $table="purchase_returns";
    protected $fillable =['purchases_id', 'supplier_id', 'purchase_status_id', 'order_total', 'paid_amount', 'discount', 'vat', 'date', 'shipping_address', 'description'];

}
?>
