<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_StockAdjustment.php" was generated by ProBot AI.
* Date: 2/19/2025 12:00:27 PM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class StockAdjustment extends Model{
    protected $table = 'stock_adjustment';

    protected $fillable = [
        // '', collumn name
    ];


}
?>
