<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Stock.php" was generated by ProBot AI.
* Date: 2/19/2025 11:58:38 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Stock extends Model{
    protected $table="stocks";
    protected $fillable =['product_id', 'transaction_type_id', 'warehouse_id', 'qty', 'uom_id', 'remark'];

    public function products(){
        return  $this->belongsTo(Product::class, 'product_id');
    }


}
?>
