<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/manufacturer/_index.blade.php" was generated by ProBot AI.
* Date: 2/18/2025 1:03:21 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Manufacturer')
@section('style')


@endsection
@section('page')
<a href="{{route('manufacturers.create')}}">New Manufacturer</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Phone</th>
			<th>Email</th>
			<th>Address</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($manufacturers as $manufacturer)
		<tr>
			<td>{{$manufacturer->id}}</td>
			<td>{{$manufacturer->name}}</td>
			<td>{{$manufacturer->phone}}</td>
			<td>{{$manufacturer->email}}</td>
			<td>{{$manufacturer->address}}</td>
			<td>{{$manufacturer->created_at}}</td>
			<td>{{$manufacturer->updated_at}}</td>

			<td>
			<form action = "{{route('manufacturers.destroy',$manufacturer->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('manufacturers.show',$manufacturer->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('manufacturers.edit',$manufacturer->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
